### ISSUE TITLE
Error validating reset password token

### ISSUE THREAD

**Issue by iAnthonyCoder** [cornflourblue/react-signup-verification-boilerplate#1]
This error appears when i tri to open the resetPassword component

react-dom.development.js:21 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

How to fix?

Thanks

**Comment by cornflourblue** [comment]
I've just re-retested the app and it's working fine for me including the forgot password and reset password functionality. Have you made changes to the code?

**Comment by dylanrychlik** [comment]
I get this error for profile update, not password reset
